# Generated by Django 6.1 on 2026-08-25 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('PENDING', 'pending'), ('CONFIRMED', 'confirmed'), ('SHIPPED', 'shipped'), ('DELIVERED', 'delivered'), ('CANCELLED', 'cancelled')], default='PENDING', max_length=20),
        ),
    ]
